# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = K:\Tools\mingw64\bin\cmake.exe

# The command to remove a file.
RM = K:\Tools\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = K:\Projects\pyart_cpp_extension

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = K:\Projects\pyart_cpp_extension

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	K:\Tools\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	K:\Tools\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start K:\Projects\pyart_cpp_extension\CMakeFiles K:\Projects\pyart_cpp_extension\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start K:\Projects\pyart_cpp_extension\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pyartkit_cpp

# Build rule for target.
pyartkit_cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 pyartkit_cpp
.PHONY : pyartkit_cpp

# fast build rule for target.
pyartkit_cpp/fast:
	$(MAKE) $(MAKESILENT) -f src\CMakeFiles\pyartkit_cpp.dir\build.make src/CMakeFiles/pyartkit_cpp.dir/build
.PHONY : pyartkit_cpp/fast

#=============================================================================
# Target rules for targets named test_canvas

# Build rule for target.
test_canvas: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_canvas
.PHONY : test_canvas

# fast build rule for target.
test_canvas/fast:
	$(MAKE) $(MAKESILENT) -f tests\CMakeFiles\test_canvas.dir\build.make tests/CMakeFiles/test_canvas.dir/build
.PHONY : test_canvas/fast

#=============================================================================
# Target rules for targets named test_geometry

# Build rule for target.
test_geometry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 test_geometry
.PHONY : test_geometry

# fast build rule for target.
test_geometry/fast:
	$(MAKE) $(MAKESILENT) -f tests\CMakeFiles\test_geometry.dir\build.make tests/CMakeFiles/test_geometry.dir/build
.PHONY : test_geometry/fast

#=============================================================================
# Target rules for targets named pyartkit_cpp_example

# Build rule for target.
pyartkit_cpp_example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 pyartkit_cpp_example
.PHONY : pyartkit_cpp_example

# fast build rule for target.
pyartkit_cpp_example/fast:
	$(MAKE) $(MAKESILENT) -f examples\CMakeFiles\pyartkit_cpp_example.dir\build.make examples/CMakeFiles/pyartkit_cpp_example.dir/build
.PHONY : pyartkit_cpp_example/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... pyartkit_cpp
	@echo ... pyartkit_cpp_example
	@echo ... test_canvas
	@echo ... test_geometry
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

